### ISSUE TITLE
App breaks if trying to upgrade

### ISSUE THREAD

**Issue by Cyberdada** [ShinDarth/Othello#7]
Hi, 
I tried to upgrade to latest angularjs and latest decorators, and then I get 

Error: [$injector:unpr] Unknown provider: tProvider <- t

my package.json deps:

 "angular": "~1.7.4"
  },
  "devDependencies": {
    "@types/angular": "~1.6.50",
    "angular-ts-decorators": "~3.7.7",
    "awesome-typescript-loader": "^5.2.1",
    "bower": "^1.8.4",
    "http-server": "^0.11.1",
    "jasmine-core": "^3.2.1",
    "karma": "^3.0.0",
    "karma-chrome-launcher": "^2.2.0",
    "karma-firefox-launcher": "^1.1.0",
    "karma-jasmine": "^1.1.2",
    "karma-junit-reporter": "^1.2.0",
    "protractor": "^5.4.1",
    "source-map-loader": "^0.2.4",
    "typescript": "^3.0.3",
    "webpack": "^4.18.0",
    "webpack-cli": "^3.1.0"

**Comment by FrancescoBorzi** [comment]
@Cyberdada I suggest to ask such kind of questions on Stackoverflow, this issue tracker is only for issues related to Othello. Feel free to send me the link of your question and I will try to help you.
